from _solve import Block

Board1_4x4 = (
	( (1, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_BOTTOM) ),
	( (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_TOP_LEFT) ),
	( (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_LEFT) ),
	( (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_TOP), (16, None) )
)

Solution1_4x4 = (
	(1, 4, 7, 15),
	(12, 11, 14, 6),
	(8, 10, 2, 3),
	(9, 5, 13, 16)
)

Board2_4x4 = (
	( (1, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_LEFT) ),
	( (None, Block.DIRECTION_BOTTOM), (2, Block.DIRECTION_TOP), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT) ),
	( (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP) ),
	( (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP_RIGHT), (16, None) ),
)
Solution2_4x4 = (
	(1, 3, 4, 14),
	(6, 2, 5, 11),
	(7, 13, 8, 10),
	(15, 12, 9, 16)
)

TestLinks1 = (
	( (1, Block.DIRECTION_BOTTOM_RIGHT), (3, Block.DIRECTION_RIGHT), (4, Block.DIRECTION_BOTTOM), (14, Block.DIRECTION_BOTTOM_LEFT) ),
	( (6, Block.DIRECTION_BOTTOM), (2, Block.DIRECTION_TOP), (None, Block.DIRECTION_LEFT), (11, Block.DIRECTION_BOTTOM_LEFT) ),
	( (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (8, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP) ),
	( (15, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP_RIGHT), (16, None) ),
)

TestLinks1_NotLinking = (
	(False, False, True, False),
	(True, False, True, True),
	(True, True, True, True),
	(False, True, True, False)
)

TestLinks1_NotLinked = (
	(False, False, False, True),
	(True, False, True, True),
	(True, True, True, True),
	(False, True, True, False)
)

Board3_16x16 = (
	((181, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM), (136, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (50, Block.DIRECTION_BOTTOM_RIGHT), (64, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM), (28, Block.DIRECTION_BOTTOM), (137, Block.DIRECTION_BOTTOM_RIGHT), (244, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT)),
	((95, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM), (19, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM), (79, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_RIGHT), (74, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_LEFT), (8, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_BOTTOM), (239, Block.DIRECTION_BOTTOM_LEFT)),
	((None, Block.DIRECTION_RIGHT), (195, Block.DIRECTION_RIGHT), (10, Block.DIRECTION_TOP_RIGHT), (214, Block.DIRECTION_BOTTOM), (106, Block.DIRECTION_BOTTOM), (56, Block.DIRECTION_RIGHT), (198, Block.DIRECTION_BOTTOM), (196, Block.DIRECTION_RIGHT), (157, Block.DIRECTION_BOTTOM), (58, Block.DIRECTION_LEFT), (60, Block.DIRECTION_BOTTOM_LEFT), (156, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_LEFT), (197, Block.DIRECTION_LEFT)),
	((None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_LEFT), (96, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (241, Block.DIRECTION_TOP_RIGHT), (160, Block.DIRECTION_BOTTOM_LEFT), (147, Block.DIRECTION_BOTTOM), (34, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_RIGHT), (119, Block.DIRECTION_TOP), (None, Block.DIRECTION_BOTTOM_LEFT), (84, Block.DIRECTION_BOTTOM), (86, Block.DIRECTION_BOTTOM), (222, Block.DIRECTION_BOTTOM)),
	((None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (62, Block.DIRECTION_BOTTOM_RIGHT), (211, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM), (23, Block.DIRECTION_LEFT), (61, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_TOP_RIGHT), (3, Block.DIRECTION_LEFT), (25, Block.DIRECTION_BOTTOM)),
	((39, Block.DIRECTION_BOTTOM), (246, Block.DIRECTION_BOTTOM), (175, Block.DIRECTION_RIGHT), (176, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP_LEFT), (76, Block.DIRECTION_RIGHT), (77, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_LEFT)),
	((None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (80, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP_LEFT), (17, Block.DIRECTION_TOP_LEFT), (200, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (155, Block.DIRECTION_TOP), (201, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (132, Block.DIRECTION_LEFT), (112, Block.DIRECTION_BOTTOM)),
	((None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (41, Block.DIRECTION_TOP), (216, Block.DIRECTION_RIGHT), (178, Block.DIRECTION_RIGHT), (63, Block.DIRECTION_TOP), (None, Block.DIRECTION_BOTTOM_RIGHT), (180, Block.DIRECTION_TOP_LEFT), (140, Block.DIRECTION_BOTTOM), (5, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_TOP), (227, Block.DIRECTION_TOP_LEFT), (46, Block.DIRECTION_BOTTOM), (179, Block.DIRECTION_LEFT), (226, Block.DIRECTION_LEFT)),
	((None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_BOTTOM), (92, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_TOP_LEFT), (148, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_RIGHT), (105, Block.DIRECTION_TOP_LEFT), (90, Block.DIRECTION_LEFT), (51, Block.DIRECTION_LEFT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_BOTTOM)),
	((124, Block.DIRECTION_BOTTOM_RIGHT), (183, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_BOTTOM_LEFT), (12, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_RIGHT), (117, Block.DIRECTION_BOTTOM_LEFT), (1, Block.DIRECTION_TOP_RIGHT), (169, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP_LEFT), (103, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_RIGHT), (66, Block.DIRECTION_BOTTOM), (102, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (32, Block.DIRECTION_TOP_LEFT)),
	((None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (172, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_LEFT), (256, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_BOTTOM_LEFT), (99, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (109, Block.DIRECTION_LEFT), (238, Block.DIRECTION_TOP)),
	((15, Block.DIRECTION_RIGHT), (188, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (118, Block.DIRECTION_TOP_RIGHT), (230, Block.DIRECTION_RIGHT), (134, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_RIGHT), (159, Block.DIRECTION_TOP), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (187, Block.DIRECTION_LEFT), (68, Block.DIRECTION_BOTTOM), (189, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT), (88, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_TOP)),
	((94, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_BOTTOM_LEFT), (55, Block.DIRECTION_TOP), (None, Block.DIRECTION_LEFT), (168, Block.DIRECTION_TOP), (141, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_LEFT), (194, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_TOP), (47, Block.DIRECTION_LEFT), (87, Block.DIRECTION_TOP), (250, Block.DIRECTION_LEFT)),
	((203, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM), (207, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_LEFT), (162, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (163, Block.DIRECTION_LEFT), (None, Block.DIRECTION_TOP), (67, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_BOTTOM), (152, Block.DIRECTION_LEFT), (26, Block.DIRECTION_LEFT)),
	((None, Block.DIRECTION_TOP_RIGHT), (165, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (166, Block.DIRECTION_RIGHT), (167, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_RIGHT), (173, Block.DIRECTION_TOP_RIGHT), (44, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_LEFT), (193, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (45, Block.DIRECTION_TOP), (151, Block.DIRECTION_TOP), (113, Block.DIRECTION_TOP)),
	((None, Block.DIRECTION_TOP), (209, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_LEFT), (171, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_LEFT), (None, Block.DIRECTION_TOP_RIGHT), (100, Block.DIRECTION_RIGHT), (126, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP_RIGHT), (210, Block.DIRECTION_TOP_LEFT), (None, Block.DIRECTION_TOP_LEFT)),
)

Solution3_16x16 = (
	(181, 245, 136, 78, 50, 64, 33, 243, 225, 21, 28, 137, 244, 115, 49, 114),
	(95, 182, 19, 11, 79, 37, 74, 75, 242, 20, 72, 120, 73, 8, 2, 239),
	(59, 195, 10, 214, 106, 56, 198, 196, 157, 58, 60, 156, 9, 138, 57, 197),
	(82, 81, 96, 36, 107, 65, 241, 160, 147, 34, 83, 119, 139, 84, 86, 222),
	(24, 213, 62, 211, 224, 212, 161, 23, 61, 22, 71, 70, 4, 85, 3, 25),
	(39, 246, 175, 176, 229, 254, 18, 76, 77, 38, 228, 218, 253, 233, 131, 232),
	(133, 111, 42, 177, 80, 54, 35, 17, 200, 89, 219, 155, 201, 234, 132, 112),
	(40, 247, 41, 216, 178, 63, 98, 180, 140, 5, 127, 217, 227, 46, 179, 226),
	(205, 52, 206, 92, 121, 91, 199, 53, 148, 128, 105, 90, 51, 129, 130, 31),
	(124, 183, 14, 12, 116, 117, 1, 169, 97, 103, 29, 66, 102, 220, 30, 32),
	(123, 110, 13, 172, 122, 256, 240, 154, 158, 99, 104, 108, 252, 237, 109, 238),
	(15, 188, 16, 118, 230, 134, 190, 159, 192, 231, 187, 68, 189, 191, 88, 221),
	(94, 249, 48, 93, 143, 55, 248, 168, 141, 174, 142, 194, 251, 47, 87, 250),
	(203, 164, 207, 144, 153, 202, 162, 145, 146, 163, 27, 67, 186, 149, 152, 26),
	(7, 165, 135, 215, 166, 167, 184, 173, 44, 6, 43, 193, 185, 45, 151, 113),
	(204, 209, 208, 171, 235, 255, 125, 170, 236, 100, 126, 69, 101, 150, 210, 223)
)

BoardI = (((1, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM_LEFT), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_LEFT)), ((None, Block.DIRECTION_RIGHT), (None, Block.DIRECTION_TOP), (None, Block.DIRECTION_BOTTOM), (None, Block.DIRECTION_BOTTOM)), ((None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_TOP_RIGHT), (None, Block.DIRECTION_BOTTOM_RIGHT), (None, Block.DIRECTION_LEFT)), ((None, Block.DIRECTION_TOP), (None, Block.DIRECTION_TOP), (14, Block.DIRECTION_TOP), (16, Block.DIRECTION_TOP)))
SolutionI = (
	(1,6, 12, 11),
	(7, 5, 13, 8),
	(3, 10, 15, 9),
	(2, 4, 14, 16)
)
